export const IPC_CHANNELS = {
  AUTH_LOGIN: "auth:login",
  AUTH_LOGOUT: "auth:logout",
  AUTH_STATUS: "auth:status",
  CONNECTION_TEST: "app:connection-test",
  APP_INFO: "app:info",
  SESSION_START: "tracking:start",
  SESSION_STOP: "tracking:stop",
  TRACKING_EVENT: "tracking:event",
  SESSION_STATUS: "tracking:status",
  TRACKING_PROJECTS: "tracking:projects",
  TRACKING_SYNC_STATUS: "tracking:sync-status",
  TRACKING_DEBUG_LAST_EVENTS: "tracking:debug:last-events",
  TRACKING_CONSENT_STATUS: "tracking:consent-status",
  TRACKING_CONSENT_ACCEPT: "tracking:consent-accept",
  TRACKING_RECENT_TASKS: "tracking:recent-tasks",
  TRACKING_WORK_SUMMARY: "tracking:work-summary",
  SYNC_NOW: "tracking:sync",
  NOTIFICATION_SOUND_ENABLED_GET: "app:notification-sound-enabled",
  NOTIFICATION_SOUND_ENABLED_SET: "app:notification-sound-enabled-set",
  WEB_NOTIFICATIONS_STATUS: "app:web-notifications-status",
  APP_UPDATE_STATUS: "app:update-status",
  APP_UPDATE_CHECK: "app:update-check",
  APP_UPDATE_DOWNLOAD: "app:update-download",
  APP_UPDATE_INSTALL: "app:update-install",
  APP_OPEN_EXTERNAL: "app:open-external"
} as const;
